bitiso-orig/bitiso/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('torrent.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bitiso-orig/torrent/urls.py
# urls.py

from django.urls import path, include
from django.views.generic import TemplateView
from .views import (
    # Homepage
    HomePageView,

    # Torrent views
    TorrentListView, TorrentDetailView, TorrentCreateView, TorrentUpdateView, TorrentDeleteView,
    file_upload, download_torrent, delete_torrents, search_view,

    # Project views
    ProjectListView, ProjectDetailBySlugView, ProjectCreateView, ProjectUpdateView, ProjectDeleteView,

    # Auth views
    login_view, logout_view, register_view,

    # Dashboard
    dashboard, dashboard_bulk_action, set_category, set_project
)

app_name = 'bitiso'


urlpatterns = [
    # Public routes (available to everyone)
    path('', HomePageView.as_view(), name='torrent_homepage'),  # Home page
    path('torrents/', TorrentListView.as_view(), name='torrent_list'),  # List all torrents
    path('torrents/search/', search_view, name='torrent_search'),  # Search torrents
    path('torrents/<slug>/', TorrentDetailView.as_view(), name='torrent_detail'),  # Torrent detail view
    path('projects/', ProjectListView.as_view(), name='project_list'),  # List all projects
    path('projects/<slug:project_slug>/', ProjectDetailBySlugView.as_view(), name='project_detail_by_slug'),

    # Static pages
    path('about/', TemplateView.as_view(template_name="bt/about.html"), name='static_about'),  # About page
    path('faq/', TemplateView.as_view(template_name="bt/faq.html"), name='static_faq'),  # FAQ page
    path('contact/', TemplateView.as_view(template_name="bt/contact.html"), name='static_contact'),  # Contact page

    # Torrent management routes (authenticated)
    path('manage/torrents/create/', TorrentCreateView.as_view(), name='manage_torrent_create'),  # Create a new torrent
    path('manage/torrents/<slug:slug>/edit/', TorrentUpdateView.as_view(), name='manage_torrent_edit'),  # Edit an existing torrent
    path('manage/torrents/<slug:slug>/delete/', TorrentDeleteView.as_view(), name='manage_torrent_delete'),  # Delete a torrent
    path('manage/torrents/upload/', file_upload, name='manage_torrent_upload'),  # Upload a torrent file
    path('manage/torrents/download/', download_torrent, name='manage_torrent_download'),  # Download a torrent file
    path('manage/torrents/delete/', delete_torrents, name='manage_torrent_bulk_delete'),  # Bulk delete torrents
    # Torrent management routes (authenticated)
    path('manage/torrents/bulk-action/', dashboard_bulk_action, name='manage_dashboard_bulk_action'),  # Bulk actions
    path('manage/torrents/set-category/', set_category, name='manage_dashboard_set_category'),
    path('manage/torrents/set-project/', set_project, name='manage_dashboard_set_project'),

    # Project management routes (authenticated)
    path('manage/projects/create/', ProjectCreateView.as_view(), name='manage_project_create'),  # Create a new project
    path('manage/projects/<slug:slug>/edit/', ProjectUpdateView.as_view(), name='manage_project_edit'),  # Edit an existing project
    path('manage/projects/<slug:slug>/delete/', ProjectDeleteView.as_view(), name='manage_project_delete'),  # Delete a project

    # Management dashboard
    path('manage/', dashboard, name='manage_dashboard'),  # Management dashboard

    # Authentication routes
    path('login/', login_view, name='auth_login'),  # User login
    path('logout/', logout_view, name='auth_logout'),  # User logout
    path('register/', register_view, name='auth_register'),  # User registration
]

bitiso/urls.py
# bitiso/urls.py

import os
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from core.pages.views import HomePageView, PageDetailView, PageUpdateView, redirect_to_language_home
from django.conf.urls.static import static
from django.conf import settings
from torrents.views.torrents import serve_torrent_file


from dotenv import load_dotenv  # python-dotenv
load_dotenv()  # Loads variables from the .env file


# Get the accounts path from the environment variable, with a default fallback
accounts_path = os.getenv('ACCOUNTS_PATH', 'accounts/')
admin_path = os.getenv('ADMIN_PATH', 'admin/')


urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),  # Language switcher
    path('', redirect_to_language_home),  # Redirect root URL to language-specific home page
    
    # Add serve_torrent_file outside i18n_patterns to avoid language prefix
    path('t/<path:filename>', serve_torrent_file, name='serve_torrent_file'),
] 

# Serving static and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# i18n URL patterns for language-prefixed routes (like /fr/, /en/)
urlpatterns += i18n_patterns(
    path('', HomePageView.as_view(), name='home'),  # Home page URL should be named 'home'
    path(admin_path, admin.site.urls),  # Use the variable for the admin path
    path(accounts_path, include('core.accounts.urls')),  # Accounts app paths

    path('profiles/', include('bitiso_user_profiles.urls')),  # Ensure you include the bitiso_user_profiles URLs

    # Project, category, and tracker routes
    path('torrents/', include('torrents.urls.torrents')),  # Torrents app URLs
    path('projects/', include('torrents.urls.projects')),  # Project URLs
    path('categories/', include('torrents.urls.categories')),  # Category URLs
    path('trackers/', include('torrents.urls.trackers')),  # Tracker URLs
    
    # Pages URL patterns
    path('<slug:slug>/', PageDetailView.as_view(), name='page_detail'),
    path('<slug:slug>/edit/', PageUpdateView.as_view(), name='page_edit'),  # Ensure consistency here

)

torrents/urls.py
# from django.urls import path
# #from . import views
# from torrents import views
# from .views import upload_local_torrent, import_torrent_from_url

# urlpatterns = [
#     # Torrent URLs
#     path('', views.TorrentListView.as_view(), name='torrent_list'),
#     path('<slug:slug>/', views.TorrentDetailView.as_view(), name='torrent_detail'),
#     path('<slug:slug>/create/', views.TorrentCreateView.as_view(), name='torrent_create'),
#     path('<slug:slug>/edit/', views.TorrentUpdateView.as_view(), name='torrent_edit'),
#     path('<slug:slug>/delete/', views.TorrentDeleteView.as_view(), name='torrent_delete'),

#     # Project URLs
#     path('projects/', views.ProjectListView.as_view(), name='project_list'),
#     path('projects/create/', views.ProjectCreateView.as_view(), name='project_create'),
#     path('projects/<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
#     path('projects/<int:pk>/edit/', views.ProjectUpdateView.as_view(), name='project_edit'),
#     path('projects/<int:pk>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),

#     # Category URLs
#     path('categories/', views.CategoryListView.as_view(), name='category_list'),
#     path('categories/create/', views.CategoryCreateView.as_view(), name='category_create'),
#     path('categories/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
#     path('categories/<int:pk>/edit/', views.CategoryUpdateView.as_view(), name='category_edit'),
#     path('categories/<int:pk>/delete/', views.CategoryDeleteView.as_view(), name='category_delete'),

#     # Tracker URLs
#     path('trackers/', views.TrackerListView.as_view(), name='tracker_list'),
#     path('trackers/create/', views.TrackerCreateView.as_view(), name='tracker_create'),
#     path('trackers/<int:pk>/', views.TrackerDetailView.as_view(), name='tracker_detail'),
#     path('trackers/<int:pk>/edit/', views.TrackerUpdateView.as_view(), name='tracker_edit'),
#     path('trackers/<int:pk>/delete/', views.TrackerDeleteView.as_view(), name='tracker_delete'),

#     path('upload/', upload_local_torrent, name='upload_local_torrent'),
#     path('import-from-url/', import_torrent_from_url, name='import_torrent_from_url'),
# ]

bitiso-orig/torrent/forms.py
from django import forms
from .models import Category, Project, Torrent

from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class SearchForm(forms.Form):
    query = forms.CharField(label="Search", max_length=100, min_length=2)

    def clean_query(self):
        query = self.cleaned_data.get('query')
        if len(query) < 2:
            raise forms.ValidationError("La recherche doit contenir au moins 2 caractères.")
        return query


class SetCategoryForm(forms.Form):
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True, label="Category")


class SetProjectForm(forms.Form):
    project = forms.ModelChoiceField(
        queryset=Project.objects.all(),
        required=True,
        label="Project"
    )


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label=_("Username"),
        max_length=254,
        widget=forms.TextInput(attrs={'class': 'form-control'})
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control'})
    )


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class FileUploadForm(forms.Form):
    file = forms.FileField(label='Select a file')

class URLDownloadForm(forms.Form):
    url = forms.URLField(label='URL to Download')

class TorrentActionForm(forms.Form):
    torrent_ids = forms.MultipleChoiceField(
        widget=forms.CheckboxSelectMultiple,
        choices=[],
        required=False
    )
    action = forms.ChoiceField(
        choices=[('delete', 'Delete'), ('set_category', 'Set Category'), ('set_project', 'Set Project')],
        required=True
    )
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=False)
    project = forms.ModelChoiceField(queryset=Project.objects.all(), required=False)

    def __init__(self, *args, **kwargs):
        torrent_choices = kwargs.pop('torrent_choices', [])
        super().__init__(*args, **kwargs)
        self.fields['torrent_ids'].choices = torrent_choices

from django import forms
from .models import Project

class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['name', 'description', 'website_url', 'website_url_download', 'website_url_repo', 'image']

bitiso-orig/torrent/views/category_views.py
# views/category_views.py

from django.views.generic import ListView
from ..models import Category, Torrent

class CategoryListView(ListView):
    model = Category
    template_name = 'category/category_list.html'
    context_object_name = 'categories'

class CategoryDetailView(ListView):
    model = Torrent
    template_name = 'category/category_detail.html'
    context_object_name = 'torrent_list'
    paginate_by = 40

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['category_id'])
        return Torrent.objects.filter(is_active=True, category=self.category).order_by('-creation')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category'] = self.category
        return context

bitiso-orig/torrent/views/dashboard_views.py
# views/dashboard_views.py
import os
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from ..models import Torrent, Category, Project
from ..forms import FileUploadForm, URLDownloadForm
from ..services.torrent_service import TorrentService
from django.conf import settings

# For all actions related to the user's personal dashboard (managing torrents, viewing stats, etc.).

@login_required
def dashboard(request):
    user_torrents = Torrent.objects.filter(uploader=request.user).order_by('-creation')
    torrent_count = user_torrents.count()
    categories = Category.objects.all()
    projects = Project.objects.all()

    if request.method == 'POST':
        action = request.POST.get('action')
        torrent_ids = request.POST.getlist('torrent_ids')

        if action == 'delete':
            Torrent.objects.filter(id__in=torrent_ids, uploader=request.user).delete()
            messages.success(request, "Selected torrents have been deleted.")
        elif action == 'activate':
            Torrent.objects.filter(id__in=torrent_ids, uploader=request.user).update(is_active=True)
            messages.success(request, "Selected torrents have been activated.")
        elif action == 'deactivate':
            Torrent.objects.filter(id__in=torrent_ids, uploader=request.user).update(is_active=False)
            messages.success(request, "Selected torrents have been deactivated.")
        elif action == 'set_category':
            category_id = request.POST.get('category_id')
            if category_id:
                category = Category.objects.get(id=category_id)
                Torrent.objects.filter(id__in=torrent_ids).update(category=category)
                messages.success(request, "Category updated successfully.")
        elif action == 'set_project':
            project_id = request.POST.get('project_id')
            if project_id:
                project = Project.objects.get(id=project_id)
                Torrent.objects.filter(id__in=torrent_ids).update(project=project)
                messages.success(request, "Project updated successfully.")
        return redirect('bitiso:manage_dashboard')

    form = FileUploadForm()
    url_form = URLDownloadForm()

    return render(request, 'user/dashboard.html', {
        'torrents': user_torrents,
        'torrent_count': torrent_count,
        'form': form,
        'url_form': url_form,
        'categories': categories,
        'projects': projects
    })

@login_required
def delete_torrents(request):
    if request.method == 'POST':
        torrent_ids = request.POST.getlist('torrent_ids')
        if torrent_ids:
            Torrent.objects.filter(id__in=torrent_ids, uploader=request.user).delete()
            messages.success(request, "Selected torrents have been deleted.")
        else:
            messages.warning(request, "No torrents were selected for deletion.")
    return redirect('dashboard')

# Assurez-vous que le répertoire settings.MEDIA_TORRENT existe
os.makedirs(settings.MEDIA_TORRENT, exist_ok=True)


def dashboard_bulk_action(request):
    if request.method == 'POST':
        torrent_ids = request.POST.getlist('torrent_ids')
        action = request.POST.get('action')

        if not torrent_ids:
            messages.error(request, 'No torrents selected for action.')
            return redirect('bitiso:manage_dashboard')

        torrents = Torrent.objects.filter(id__in=torrent_ids)

        if action == 'delete':
            torrents.delete()
            messages.success(request, 'Selected torrents have been deleted.')
        elif action == 'activate':
            torrents.update(is_active=True)
            messages.success(request, 'Selected torrents have been activated.')
        elif action == 'deactivate':
            torrents.update(is_active=False)
            messages.success(request, 'Selected torrents have been deactivated.')
        else:
            messages.error(request, 'Invalid action selected.')

    return redirect('bitiso:manage_dashboard')  # Redirect back to the dashboard


def set_category(request):
    if request.method == 'POST':
        category_id = request.POST.get('category')
        # Logic to set category
        messages.success(request, 'Category has been updated.')

    return redirect('bitiso:manage_dashboard')


def set_project(request):
    if request.method == 'POST':
        project_id = request.POST.get('project')
        # Logic to set project
        messages.success(request, 'Project has been updated.')

    return redirect('bitiso:manage_dashboard')

bitiso-orig/torrent/views/homepage_views.py
from django.views.generic import ListView
from ..models import Torrent
from ..mixins import RateLimitMixin
from ..forms import SearchForm


def get_top_seeded_torrents():
    return Torrent.objects.filter(is_active=True).order_by('-seed')[:10]  # Query for top seeded torrents


class HomePageView(ListView):
    model = Torrent
    template_name = 'bt/homepage.html'
    context_object_name = 'torrent_list'
    paginate_by = 40  # Adjust as needed

    def get_queryset(self):
        torrents = Torrent.objects.filter(is_active=True).order_by('-creation')
        query = self.request.GET.get('query')

        # If there's a search query, filter by name
        if query:
            torrents = torrents.filter(name__icontains=query)

        return torrents

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_form()  # Add the search form to the context
        context['top_seeded_torrent_list'] = get_top_seeded_torrents()  # Add top seeded torrents to the context
        return context

    def get_form(self):
        return SearchForm(self.request.GET or None)  # Create or populate the search form

bitiso-orig/torrent/templates/project/project_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<style>

/* Adjusting project container for larger screens */
.project-container,
.torrent-table-wrapper {
    max-width: 1000px; /* Constrain the width */
    margin: 0 auto; /* Center the container */
    padding: 0 20px; /* Add some padding for smaller screens */
}

/* Existing project container styles */
.project-container {
    display: flex;
    align-items: center;
    flex-wrap: nowrap; /* Prevent wrapping on larger screens */
}

.project-image-container {
    flex-shrink: 0;
    margin-right: 20px;
    width: 150px; /* Reduced width for the image */
    height: 150px; /* Reduced height for the image */
}

.project-image-container img {
    width: 100%;
    height: 100%;
    object-fit: contain;
}

.project-details {
    flex-grow: 1;
    text-align: left;
}

/* Responsive adjustments */
@media (max-width: 600px) {
    .project-container {
        flex-direction: column; /* Stack items vertically on smaller screens */
        align-items: center; /* Center items horizontally */
    }

    .project-image-container {
        margin-right: 0; /* Remove margin when stacking vertically */
        margin-bottom: 10px; /* Add space below the image */
        width: 100px; /* Smaller image on mobile */
        height: 100px;
    }

    .project-details {
        text-align: center; /* Center text on smaller screens */
    }
}

/* Ensure the torrent table does not stretch too wide on large screens */
.torrent-table-wrapper {
    max-width: 1000px; /* Constrain the width of the table wrapper */
    margin: 0 auto; /* Center the table on the page */
    padding: 0 20px; /* Add some padding for smaller screens */
    overflow-x: auto; /* Allows horizontal scrolling on smaller screens */
}

.torrent-table {
    width: 100%;
    border-collapse: collapse; /* Removes extra spacing between cells */
}

.torrent-table th,
.torrent-table td {
    padding: .5em 1em; /* Adjusted padding */
    text-align: left;
    border-bottom: 1px solid #eee; /* Light border for row separation */
    /* border-left: 1px solid #cbcbcb; /* Left border */
    border-width: 0 0 0 1px; /* Border width adjusted */
    font-size: inherit; /* Inherit font size */
    margin: 0; /* Reset margin */
    overflow: visible; /* Ensure overflow is visible */
}

.torrent-table th {
    font-weight: bold;
    background-color: rgb(63, 68, 71)


}
/*
.torrent-table tr:hover {
    background-color: #f9f9f9; /* Light background on row hover
}
*/

.torrent-table .no-wrap {
    white-space: nowrap; /* Prevents text wrapping in this cell */
}

.torrent-table img {
    vertical-align: middle;
    margin-right: 8px;
    width: 20px; /* Adjust the size of the image as needed */
}

.torrent-table .center-content-magnet {
    text-align: center;
}

.torrent-table .seed,
.torrent-table .leech {
    text-align: center;
}

</style>

<div class="project-container">

    <div class="project-image-container">

        {% if project.medium_image %}
        <img src="{{ project.medium_image.url }}" alt="{{ project.name }}">
        {% else %}
        <img src="" alt="{{ project.name }}">
        {% endif %}
    </div>
    <div class="project-details">
        <h1>{{ project.name }}</h1>
        <p>{{ project.description }}</p>
        <p><strong>Website:</strong> <a href="{{ project.website_url }}">{{ project.website_url }}</a></p>
        <p><strong>Download Page:</strong> <a href="{{ project.website_url_download }}">{{ project.website_url_download }}</a></p>
        <p><strong>Repository:</strong> <a href="{{ project.website_url_repo }}">{{ project.website_url_repo }}</a></p>
        <a href="{% url 'bitiso:project_list' %}" class="project-back-link">Back to Project List</a>
    </div>
</div>


    <h2 style="text-align: center;">Torrents </h2>
<div class="torrent-table-wrapper">
    <table class="torrent-table">
        <thead>
            <tr>
                <th></th>
                <th>Name</th>
                <th>Size</th>
                <th>Date</th>
                <th>T</th>
                <th>M</th>
                <th>Seed</th>
                <th>Leech</th>
            </tr>
        </thead>
        <tbody>
            {% for torrent in torrents %}
            <tr>
                <td><a href="/category/{{ torrent.category.id }}">{{ torrent.category.category_parent_id.name|default:"None" }}</a></td>
                <td class="no-wrap">
                    {% if torrent.project.mini_image %}
                    <img src="{{ torrent.project.mini_image.url }}" alt="">
                    {% endif %}
                    <a href="/torrents/{{ torrent.name }}">{{ torrent.name }}</a>
                </td>
                <td>{{ torrent.size | filesizeformat }}</td>
                <td class="single-line">{{ torrent.creation | date:"M. j" }}</td>
                <td><a href="{{ MEDIA_URL }}{{ torrent.metainfo_file }}">Torrent</a></td>
                <td class="center-content-magnet"><a href="{{ torrent.magnet }}"><img src="{% static 'img/icon-magnet.gif' %}" alt="Magnet link"></a></td>
                <td class="seed">{{ torrent.seed }}</td>
                <td class="leech">{{ torrent.leech }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

bitiso-orig/torrent/templates/project/project_list.html
{% extends "base.html" %}
{% block title %}Bitiso.org{% endblock %}
{% load static %}
{% block content %}
    <div class="pure-g">
        {% for project in projects %}
        <div class="pure-u-1 pure-u-md-1-3 pure-u-lg-1-4">
            <div class="project-card">
                <div class="project-name">
                    <a href="{% url 'bitiso:project_detail_by_slug' project.slug %}">
                        {{ project.name }}
                    </a>
                </div>
                {% if project.small_image %}
                <a href="{% url 'bitiso:project_detail_by_slug' project.slug %}">
                    <img src="{{ project.medium_image.url }}" alt="{{ project.name }}" class="project-image">
                </a>
                {% endif %}
                <div class="project-description">
                    {{ project.description }}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
{% endblock %}

<style>
    .project-card {
        padding: 20px;
        border: 1px solid #ddd;
        margin-bottom: 20px;
        text-align: center;
    }
    .project-name {
        font-weight: bold;
        margin-bottom: 10px;
    }
    .project-image {
        max-width: 100%;
        height: auto;
        margin-bottom: 10px;
    }
    .project-description {
        font-size: 0.9em;
        color: #666;
    }
</style>